import os
import sqlite3
import psycopg
from psycopg import sql

# Pointer to your local SQLite database
SQLITE_DB = "campus_hardware.db"

# Reads the Supabase PostgreSQL connection string set in environment
DATABASE_URL = os.getenv("DATABASE_URL")

if not DATABASE_URL:
    raise RuntimeError("DATABASE_URL environment variable is not set.")

sqlite_conn = sqlite3.connect(SQLITE_DB)
sqlite_conn.row_factory = sqlite3.Row
pg_conn = psycopg.connect(DATABASE_URL)
pg_conn.autocommit = False

try:
    pg_cur = pg_conn.cursor()
    sqlite_cur = sqlite_conn.cursor()

    # Exact table definitions translated from your SQLite schema to PostgreSQL
    table_definitions = {
        "users": [
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "username TEXT UNIQUE NOT NULL",
            "email TEXT UNIQUE NOT NULL",
            "password_hash TEXT NOT NULL",
            "salt TEXT NOT NULL",
            "hint TEXT",
            "role TEXT NOT NULL DEFAULT 'VIEWER'",
            "failed_attempts INTEGER DEFAULT 0",
            "is_locked INTEGER DEFAULT 0",
        ],
        "reset_requests": [
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "username TEXT NOT NULL",
            "email TEXT NOT NULL",
            "proposed_password TEXT NOT NULL",
            "reason TEXT",
            "requested_at TEXT NOT NULL",
        ],
        "inventory": [
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "item_name TEXT NOT NULL",
            "category TEXT NOT NULL",
            "serial_number TEXT UNIQUE NOT NULL",
            "quantity INTEGER NOT NULL DEFAULT 1",
            "min_stock INTEGER NOT NULL DEFAULT 1",
            "max_stock INTEGER NOT NULL DEFAULT 10",
            "location TEXT NOT NULL",
            "status TEXT DEFAULT 'AVAILABLE'",
            "added_by TEXT NOT NULL",
            "added_at TEXT NOT NULL",
        ],
        "maintenance": [
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "item_name TEXT NOT NULL",
            "serial_number TEXT NOT NULL",
            "vendor TEXT NOT NULL",
            "issue_description TEXT NOT NULL",
            "repair_cost DOUBLE PRECISION NOT NULL DEFAULT 0.0",
            "status TEXT DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'UNREPAIRABLE'))",
            "logged_by TEXT NOT NULL",
            "logged_at TEXT NOT NULL",
            "resolved_at TEXT",
        ],
        "borrow_logs": [
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "item_id BIGINT NOT NULL",
            "item_name TEXT NOT NULL",
            "serial_number TEXT NOT NULL",
            "borrower_name TEXT NOT NULL",
            "borrower_contact TEXT NOT NULL",
            "quantity_borrowed INTEGER NOT NULL DEFAULT 1",
            "borrow_date TEXT NOT NULL",
            "expected_return_date TEXT NOT NULL",
            "actual_return_date TEXT",
            "status TEXT DEFAULT 'BORROWED' CHECK (status IN ('PENDING', 'BORROWED', 'RETURNED', 'OVERDUE'))",
            "issued_by TEXT",
            "FOREIGN KEY (item_id) REFERENCES inventory (id)",
        ],
        "audit_logs": [
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "timestamp TEXT NOT NULL",
            "performed_by TEXT NOT NULL",
            "action TEXT NOT NULL",
            "details TEXT NOT NULL",
        ],
    }

    # 1. Create tables in Supabase PostgreSQL
    for table_name, columns in table_definitions.items():
        column_sql = sql.SQL(", ").join(sql.SQL(column) for column in columns)
        create_sql = sql.SQL("CREATE TABLE IF NOT EXISTS {} ({})").format(
            sql.Identifier(table_name), column_sql
        )
        pg_cur.execute(create_sql)

    counts = {}

    # 2. Extract from SQLite and insert into PostgreSQL
    for table_name in table_definitions.keys():
        pg_cur.execute(
            sql.SQL("SELECT COUNT(*) FROM {}").format(sql.Identifier(table_name))
        )
        destination_count = pg_cur.fetchone()[0]

        if destination_count > 0:
            raise RuntimeError(
                f"Destination table '{table_name}' in Supabase is not empty. Clean it before migrating."
            )

        # Uses standard Python string query for SQLite execution
        sqlite_cur.execute(f"SELECT * FROM {table_name}")
        rows = sqlite_cur.fetchall()
        counts[table_name] = len(rows)

        if not rows:
            continue

        source_columns = [description[0] for description in sqlite_cur.description]
        column_identifiers = sql.SQL(", ").join(
            sql.Identifier(column) for column in source_columns
        )
        placeholders = sql.SQL(", ").join(
            sql.Placeholder() for _ in source_columns
        )

        insert_sql = sql.SQL("INSERT INTO {} ({}) VALUES ({})").format(
            sql.Identifier(table_name), column_identifiers, placeholders
        )

        for row in rows:
            values = [row[column] for column in source_columns]
            pg_cur.execute(insert_sql, values)

# 3. Synchronize identity sequences so future auto-increment IDs start after existing records
    for table_name in table_definitions.keys():
        sequence_sql = sql.SQL("""
            SELECT setval(
                pg_get_serial_sequence({}, 'id'),
                COALESCE(MAX(id), 1),
                MAX(id) IS NOT NULL
            )
            FROM {}
        """).format(
            sql.Literal(table_name),
            sql.Identifier(table_name),
        )
        pg_cur.execute(sequence_sql)

    pg_conn.commit()
    print("Migration completed successfully!\n")
    for tbl, count in counts.items():
        print(f"  {tbl:<20}: {count} rows")

except Exception as e:
    pg_conn.rollback()
    print(f"Migration failed: {e}")
    raise

finally:
    sqlite_conn.close()
    pg_conn.close()